language: node_js
node_js:
    - '10'
    - '8'
install:
    - make install
script:
    - make tsc
    - make test
notifications:
    slack:
        secure: FvC7+izaG24bzEUQ7W+zIDHdXvb7+uwg0dTSGHYOxV/frodBcOPIGWUsLmFyS+InRjBy3RgzWuf6FHCuYRPabjBNy7d/pAE4f4fWxsOBJhlQVoJCPZb4075DTd8oJbSty4yFOeB1JddnFlEHGxYdY6gYYHEaNYOkVhOmJn8gfA5s7aJl/6Ld38cPTH9vvtUXmMfazqaAjuHdAtzOd5kOOsF0ttaCaGHHwA2tvQJPPFGbccvDJn8yVMGYp/sFFHAQCMQ01Tsd0ZWQ8STHSQmX86QJsHewhWoUPl4KxAFhIbqhbvx0iYheOPgnNw2sSeH9gRk1qivSQGRLLtwe6YYHWe9pzPnXgwPwsKmIv7tAoOaj8usXkiApZE2KzQhRBS7LWBP7AR6k+byXS2Oqu1wnVAnF+zFHzFsR7u4vhtscujN8xaq4aEg/boPPVkdNWjH9icRYqVKzulvxaR0O9U/Y6sv+CRi52ywyA2Bz2w/yZgoP4v/wpeMGXve2lXa2Qeg3u9TKJQm6OlyQaSYk8yMZ4e8CG1hGvxCpngdXUkmuBXICsxLe4LHedaxIfwqo3wZECY6xUcgpqITAhWJ4Ko/Gpou72ZywKllmta9qKuv7NsQ2+zUy5z3dlLTBmhLK/duohp+uHI1iHORn47Nt0l6lGbtuwAmBAwqGh7+SBV+wR2g=
