language: node_js
node_js:
    - '10'
    - '8'
install:
    - make install
script:
    - make tsc
    - make test
notifications:
    slack:
        secure: F9ioUAptWUxG2wTxGjV9QpfZS0YaYZ3xhMxD4k3Wv0Kx4k8mb47E10CK+sF1XtqW3keZU65FsEpIfk7HK8manAm97KSD3qHZ/pNpZ9ccA490fYWzjXZhg7IEk0n6l3d4yv6plDeNytlO6hRbcWrAcmY8v+B3zB4cf3CPp+ywmRDTX1CQ5zrdBu4ak0j+WAoDDwRkhukxxPoCT/6wo3BrRtORApOuNzwAeF56HBEve1rHyFuEf0vo+YKfY/cgM8kPz538KkoxEw3uBTJBOmoWyd/kjkhrUPmPOHtMub+l0Veh/EM/TPP1PwhqBSrS9TNB8vOB6Nf69LRqLuefJn4d1scAIcosm++O4j1Rqk1A4fcLM5XqzQazjLsT03ZnBSlABrntbfCsnBGT3QSWSP+EYoPJyLVJV+6lZQk/EG9TtYzYHDjwXwfdvkfCoc10asmBa7gUkzvTwbNni+Xcgp686h7tPZh5ap1Ns+8qaLwZ0BzGAVLzxBoV4nB5M2RomXPlL1zCykQDM8nMHdeRUcnjlmOKPZ0u+ATbKIi36l5ax2Z+V6A+PB1M0Z/4kFBejbzINOMfIEV5QZKzftjBjFAJutiVQLBX5yaFhuWQlQS+x7iavvNEft7H8rslfQuGWQSYqQdriVC08oVag45UPqFcTAEQxYJpwiutyFHoyXPoyp8=
        on_success: always
