language: node_js
node_js:
    - '10'
install:
    - make install
script:
    - make tsc
    - make test
notifications:
    slack:
        rooms:
            secure: tAoN3tNMuh7By9SDAcT4CynWN/uG6cb5OTn4za+3NDiDENv6WBB3Z12k1YGI6qS/5RKd/MwhIYHYnv+JcxBNv3asob+Q36+tRU340qwRbU+NlpXTFYStXwYxF86UtjrwpUJlqc+px23qKtOiOgbx1A20E9X0+oqUxzHQoA5pSPkyFFic1BJXtd88zvw2iXobIMX+65v4kQG3r5Og8cQVmWqCPn8JzvgdoPVMKItlGTVLSUplRY0EtwW/psMzKDFAHB4b7bCzOeiCgH8eXQsiVJZzj4P0FaRJJ5gCgTnFSwgGTI2aXjcx0qyqI8GSGV0vrkp/XOFIKSSFMsfCcZ0aPPhmwZTnVQ78T8mSd6D2oLldKkxYdIzejx6BdP+bSrwG/y6wiNzLZasmXYFJB9wVp5o2akp1EJwRJqIQ35iUeJ1ghA6tzCbSSqEh64uhcwBbTC1/Q58wqWgQ3/+hAknOESuKj1GdL91S/WfOxI0QZe4VEc0wcLd+S/aqgOZy5JNhpqzyQF72/65nuU49Xz8ghelaAzYsieVlkZvfEqlM9kS9tAILnFwoxFsPQqEKwK24in76I3bAcGXdC+x8mEOBB9o3otzqkmYZJJoJ0FGL83fvG7xljQ4QG+5LR7yZgqGnmfTIWRzjeeeWFFpWwFIcFz6hQAn1MVPToTqA8C4ydA4=
